name: flutter_modular
description: Smart project structure with dependency injection and route management
version: 1.2.3
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
